import = [
    "/home/onx/.config/bspwm/alacritty/colors.toml", 
    "/home/onx/.config/bspwm/alacritty/fonts.toml"
]
live_config_reload = false

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"
opacity = 0.95

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 114
lines = 40

[window.padding]
x = 10
y = 10
